/*Copyright (c) 2017-2018 wm9.com All Rights Reserved.
 This software is the confidential and proprietary information of wm9.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wm9.com*/
package com.mobi_22ndaug_dev.db123__.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.hibernate.TypeMismatchException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.DownloadResponse;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.mobi_22ndaug_dev.db123__.Alltypeswithoutspace;
import com.mobi_22ndaug_dev.db123__.service.AlltypeswithoutspaceService;


/**
 * Controller object for domain model class Alltypeswithoutspace.
 * @see Alltypeswithoutspace
 */
@RestController("db123__.AlltypeswithoutspaceController")
@Api(value = "AlltypeswithoutspaceController", description = "Exposes APIs to work with Alltypeswithoutspace resource.")
@RequestMapping("/db123__/Alltypeswithoutspace")
public class AlltypeswithoutspaceController {

    private static final Logger LOGGER = LoggerFactory.getLogger(AlltypeswithoutspaceController.class);

    @Autowired
	@Qualifier("db123__.AlltypeswithoutspaceService")
	private AlltypeswithoutspaceService alltypeswithoutspaceService;

	@ApiOperation(value = "Creates a new Alltypeswithoutspace instance.")
@RequestMapping(method = RequestMethod.POST, consumes = "multipart/form-data")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
public Alltypeswithoutspace createAlltypeswithoutspace(@RequestPart("wm_data_json") Alltypeswithoutspace alltypeswithoutspace, @RequestPart(value = "blobcol", required = false) MultipartFile _blobcol) {
		LOGGER.debug("Create Alltypeswithoutspace with information: {}" , alltypeswithoutspace);

    alltypeswithoutspace.setBlobcol(WMMultipartUtils.toByteArray(_blobcol));
		alltypeswithoutspace = alltypeswithoutspaceService.create(alltypeswithoutspace);
		LOGGER.debug("Created Alltypeswithoutspace with information: {}" , alltypeswithoutspace);

	    return alltypeswithoutspace;
	}

    @ApiOperation(value = "Returns the Alltypeswithoutspace instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Alltypeswithoutspace getAlltypeswithoutspace(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting Alltypeswithoutspace with id: {}" , id);

        Alltypeswithoutspace foundAlltypeswithoutspace = alltypeswithoutspaceService.getById(id);
        LOGGER.debug("Alltypeswithoutspace details with id: {}" , foundAlltypeswithoutspace);

        return foundAlltypeswithoutspace;
    }

    @ApiOperation(value = "Retrieves content for the given BLOB field in Alltypeswithoutspace instance" )
    @RequestMapping(value = "/{id}/content/{fieldName}", method = RequestMethod.GET, produces="application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public DownloadResponse getAlltypeswithoutspaceBLOBContent(@PathVariable("id") Integer id, @PathVariable("fieldName") String fieldName, HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, @RequestParam(value="download", defaultValue = "false") boolean download) {

        LOGGER.debug("Retrieves content for the given BLOB field {} in Alltypeswithoutspace instance" , fieldName);

        if(!WMRuntimeUtils.isLob(Alltypeswithoutspace.class, fieldName)) {
            throw new TypeMismatchException("Given field " + fieldName + " is not a valid BLOB type");
        }
        Alltypeswithoutspace alltypeswithoutspace = alltypeswithoutspaceService.getById(id);

        return WMMultipartUtils.buildDownloadResponseForBlob(alltypeswithoutspace, fieldName, httpServletRequest, download);
    }

    @ApiOperation(value = "Updates the Alltypeswithoutspace instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Alltypeswithoutspace editAlltypeswithoutspace(@PathVariable("id") Integer id, @RequestBody Alltypeswithoutspace alltypeswithoutspace) throws EntityNotFoundException {
        LOGGER.debug("Editing Alltypeswithoutspace with id: {}" , alltypeswithoutspace.getPkid());

        alltypeswithoutspace.setPkid(id);
        alltypeswithoutspace = alltypeswithoutspaceService.update(alltypeswithoutspace);
        LOGGER.debug("Alltypeswithoutspace details with id: {}" , alltypeswithoutspace);

        return alltypeswithoutspace;
    }

    @ApiOperation(value = "Updates the Alltypeswithoutspace instance associated with the given id.This API should be used when Alltypeswithoutspace instance fields that require multipart data.") 
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.POST, consumes = {"multipart/form-data"})
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Alltypeswithoutspace editAlltypeswithoutspace(@PathVariable("id") Integer id, MultipartHttpServletRequest multipartHttpServletRequest) throws EntityNotFoundException {
        Alltypeswithoutspace newAlltypeswithoutspace = WMMultipartUtils.toObject(multipartHttpServletRequest, Alltypeswithoutspace.class, "db123__");
        newAlltypeswithoutspace.setPkid(id);

        Alltypeswithoutspace oldAlltypeswithoutspace = alltypeswithoutspaceService.getById(id);
        WMMultipartUtils.updateLobsContent(oldAlltypeswithoutspace, newAlltypeswithoutspace);
        LOGGER.debug("Updating Alltypeswithoutspace with information: {}" , newAlltypeswithoutspace);

        return alltypeswithoutspaceService.update(newAlltypeswithoutspace);
    }

    @ApiOperation(value = "Deletes the Alltypeswithoutspace instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteAlltypeswithoutspace(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Alltypeswithoutspace with id: {}" , id);

        Alltypeswithoutspace deletedAlltypeswithoutspace = alltypeswithoutspaceService.delete(id);

        return deletedAlltypeswithoutspace != null;
    }

    /**
     * @deprecated Use {@link #findAlltypeswithoutspaces(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Alltypeswithoutspace instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Alltypeswithoutspace> searchAlltypeswithoutspacesByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Alltypeswithoutspaces list");
        return alltypeswithoutspaceService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Alltypeswithoutspace instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Alltypeswithoutspace> findAlltypeswithoutspaces(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Alltypeswithoutspaces list");
        return alltypeswithoutspaceService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Alltypeswithoutspace instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @RequestMapping(value="/filter", method = RequestMethod.POST, consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Alltypeswithoutspace> filterAlltypeswithoutspaces(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Alltypeswithoutspaces list");
        return alltypeswithoutspaceService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
    @RequestMapping(value = "/export/{exportType}", method = {RequestMethod.GET,  RequestMethod.POST}, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportAlltypeswithoutspaces(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return alltypeswithoutspaceService.export(exportType, query, pageable);
    }

	@ApiOperation(value = "Returns the total count of Alltypeswithoutspace instances matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
	@RequestMapping(value = "/count", method = {RequestMethod.GET, RequestMethod.POST})
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countAlltypeswithoutspaces( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Alltypeswithoutspaces");
		return alltypeswithoutspaceService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@RequestMapping(value = "/aggregations", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getAlltypeswithoutspaceAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return alltypeswithoutspaceService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service AlltypeswithoutspaceService instance
	 */
	protected void setAlltypeswithoutspaceService(AlltypeswithoutspaceService service) {
		this.alltypeswithoutspaceService = service;
	}

}

