/*Copyright (c) 2017-2018 wm9.com All Rights Reserved.
 This software is the confidential and proprietary information of wm9.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wm9.com*/
package com.mobi_22ndaug_dev.db123__;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Blobtypes generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`BLOBTYPES`")
public class Blobtypes implements Serializable {

    private Integer pkId;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobType1;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobType2;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobType3;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobType4;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobType5;
    private Boolean booleanCol;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`PK ID`", nullable = false, scale = 0, precision = 10)
    public Integer getPkId() {
        return this.pkId;
    }

    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }

    @Column(name = "`BLOB TYPE1`", nullable = true)
    public byte[] getBlobType1() {
        return this.blobType1;
    }

    public void setBlobType1(byte[] blobType1) {
        this.blobType1 = blobType1;
    }

    @Column(name = "`BLOB TYPE2`", nullable = true)
    public byte[] getBlobType2() {
        return this.blobType2;
    }

    public void setBlobType2(byte[] blobType2) {
        this.blobType2 = blobType2;
    }

    @Column(name = "`BLOB TYPE3`", nullable = true)
    public byte[] getBlobType3() {
        return this.blobType3;
    }

    public void setBlobType3(byte[] blobType3) {
        this.blobType3 = blobType3;
    }

    @Column(name = "`BLOB TYPE4`", nullable = true)
    public byte[] getBlobType4() {
        return this.blobType4;
    }

    public void setBlobType4(byte[] blobType4) {
        this.blobType4 = blobType4;
    }

    @Column(name = "`BLOB TYPE5`", nullable = true)
    public byte[] getBlobType5() {
        return this.blobType5;
    }

    public void setBlobType5(byte[] blobType5) {
        this.blobType5 = blobType5;
    }

    @Column(name = "`BOOLEAN COL`", nullable = true)
    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Blobtypes)) return false;
        final Blobtypes blobtypes = (Blobtypes) o;
        return Objects.equals(getPkId(), blobtypes.getPkId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPkId());
    }
}

