/*Copyright (c) 2017-2018 wm9.com All Rights Reserved.
 This software is the confidential and proprietary information of wm9.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wm9.com*/
package com.mobi_22ndaug_dev.db123__.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.mobi_22ndaug_dev.db123__.Alltypeswithoutspace;

/**
 * Service object for domain model class {@link Alltypeswithoutspace}.
 */
public interface AlltypeswithoutspaceService {

    /**
     * Creates a new Alltypeswithoutspace. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Alltypeswithoutspace if any.
     *
     * @param alltypeswithoutspace Details of the Alltypeswithoutspace to be created; value cannot be null.
     * @return The newly created Alltypeswithoutspace.
     */
	Alltypeswithoutspace create(@Valid Alltypeswithoutspace alltypeswithoutspace);


	/**
	 * Returns Alltypeswithoutspace by given id if exists.
	 *
	 * @param alltypeswithoutspaceId The id of the Alltypeswithoutspace to get; value cannot be null.
	 * @return Alltypeswithoutspace associated with the given alltypeswithoutspaceId.
     * @throws EntityNotFoundException If no Alltypeswithoutspace is found.
	 */
	Alltypeswithoutspace getById(Integer alltypeswithoutspaceId) throws EntityNotFoundException;

    /**
	 * Find and return the Alltypeswithoutspace by given id if exists, returns null otherwise.
	 *
	 * @param alltypeswithoutspaceId The id of the Alltypeswithoutspace to get; value cannot be null.
	 * @return Alltypeswithoutspace associated with the given alltypeswithoutspaceId.
	 */
	Alltypeswithoutspace findById(Integer alltypeswithoutspaceId);


	/**
	 * Updates the details of an existing Alltypeswithoutspace. It replaces all fields of the existing Alltypeswithoutspace with the given alltypeswithoutspace.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Alltypeswithoutspace if any.
     *
	 * @param alltypeswithoutspace The details of the Alltypeswithoutspace to be updated; value cannot be null.
	 * @return The updated Alltypeswithoutspace.
	 * @throws EntityNotFoundException if no Alltypeswithoutspace is found with given input.
	 */
	Alltypeswithoutspace update(@Valid Alltypeswithoutspace alltypeswithoutspace) throws EntityNotFoundException;

    /**
	 * Deletes an existing Alltypeswithoutspace with the given id.
	 *
	 * @param alltypeswithoutspaceId The id of the Alltypeswithoutspace to be deleted; value cannot be null.
	 * @return The deleted Alltypeswithoutspace.
	 * @throws EntityNotFoundException if no Alltypeswithoutspace found with the given id.
	 */
	Alltypeswithoutspace delete(Integer alltypeswithoutspaceId) throws EntityNotFoundException;

	/**
	 * Find all Alltypeswithoutspaces matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Alltypeswithoutspaces.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Alltypeswithoutspace> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Alltypeswithoutspaces matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Alltypeswithoutspaces.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Alltypeswithoutspace> findAll(String query, Pageable pageable);

    /**
	 * Exports all Alltypeswithoutspaces matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Alltypeswithoutspaces in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Alltypeswithoutspace.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

