/*Copyright (c) 2017-2018 wm9.com All Rights Reserved.
 This software is the confidential and proprietary information of wm9.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wm9.com*/
package com.mobi_22ndaug_dev.db123__.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.mobi_22ndaug_dev.db123__.AllTypesSmallCase;

/**
 * Service object for domain model class {@link AllTypesSmallCase}.
 */
public interface AllTypesSmallCaseService {

    /**
     * Creates a new AllTypesSmallCase. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on AllTypesSmallCase if any.
     *
     * @param allTypesSmallCase Details of the AllTypesSmallCase to be created; value cannot be null.
     * @return The newly created AllTypesSmallCase.
     */
	AllTypesSmallCase create(@Valid AllTypesSmallCase allTypesSmallCase);


	/**
	 * Returns AllTypesSmallCase by given id if exists.
	 *
	 * @param alltypessmallcaseId The id of the AllTypesSmallCase to get; value cannot be null.
	 * @return AllTypesSmallCase associated with the given alltypessmallcaseId.
     * @throws EntityNotFoundException If no AllTypesSmallCase is found.
	 */
	AllTypesSmallCase getById(Integer alltypessmallcaseId) throws EntityNotFoundException;

    /**
	 * Find and return the AllTypesSmallCase by given id if exists, returns null otherwise.
	 *
	 * @param alltypessmallcaseId The id of the AllTypesSmallCase to get; value cannot be null.
	 * @return AllTypesSmallCase associated with the given alltypessmallcaseId.
	 */
	AllTypesSmallCase findById(Integer alltypessmallcaseId);

    /**
	 * Find and return the AllTypesSmallCase for given pkId  andbyteCol  andshortCol  if exists.
	 *
	 * @param pkId value of pkId; value cannot be null.
	 * @param byteCol value of byteCol; value cannot be null.
	 * @param shortCol value of shortCol; value cannot be null.
	 * @return AllTypesSmallCase associated with the given inputs.
     * @throws EntityNotFoundException if no matching AllTypesSmallCase found.
	 */
    AllTypesSmallCase getByPkIdAndByteColAndShortCol(int pkId, Byte byteCol, Short shortCol)throws EntityNotFoundException;

	/**
	 * Updates the details of an existing AllTypesSmallCase. It replaces all fields of the existing AllTypesSmallCase with the given allTypesSmallCase.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on AllTypesSmallCase if any.
     *
	 * @param allTypesSmallCase The details of the AllTypesSmallCase to be updated; value cannot be null.
	 * @return The updated AllTypesSmallCase.
	 * @throws EntityNotFoundException if no AllTypesSmallCase is found with given input.
	 */
	AllTypesSmallCase update(@Valid AllTypesSmallCase allTypesSmallCase) throws EntityNotFoundException;

    /**
	 * Deletes an existing AllTypesSmallCase with the given id.
	 *
	 * @param alltypessmallcaseId The id of the AllTypesSmallCase to be deleted; value cannot be null.
	 * @return The deleted AllTypesSmallCase.
	 * @throws EntityNotFoundException if no AllTypesSmallCase found with the given id.
	 */
	AllTypesSmallCase delete(Integer alltypessmallcaseId) throws EntityNotFoundException;

	/**
	 * Find all AllTypesSmallCases matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching AllTypesSmallCases.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<AllTypesSmallCase> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all AllTypesSmallCases matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching AllTypesSmallCases.
     *
     * @see Pageable
     * @see Page
	 */
    Page<AllTypesSmallCase> findAll(String query, Pageable pageable);

    /**
	 * Exports all AllTypesSmallCases matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the AllTypesSmallCases in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the AllTypesSmallCase.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

