/*Copyright (c) 2017-2018 wm9.com All Rights Reserved.
 This software is the confidential and proprietary information of wm9.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wm9.com*/
package com.mobi_22ndaug_dev.db123__.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.mobi_22ndaug_dev.db123__.AllTypesSmallCase;


/**
 * ServiceImpl object for domain model class AllTypesSmallCase.
 *
 * @see AllTypesSmallCase
 */
@Service("db123__.AllTypesSmallCaseService")
@Validated
public class AllTypesSmallCaseServiceImpl implements AllTypesSmallCaseService {

    private static final Logger LOGGER = LoggerFactory.getLogger(AllTypesSmallCaseServiceImpl.class);


    @Autowired
    @Qualifier("db123__.AllTypesSmallCaseDao")
    private WMGenericDao<AllTypesSmallCase, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<AllTypesSmallCase, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "db123__TransactionManager")
    @Override
	public AllTypesSmallCase create(AllTypesSmallCase allTypesSmallCase) {
        LOGGER.debug("Creating a new AllTypesSmallCase with information: {}", allTypesSmallCase);
        AllTypesSmallCase allTypesSmallCaseCreated = this.wmGenericDao.create(allTypesSmallCase);
        return allTypesSmallCaseCreated;
    }

	@Transactional(readOnly = true, value = "db123__TransactionManager")
	@Override
	public AllTypesSmallCase getById(Integer alltypessmallcaseId) throws EntityNotFoundException {
        LOGGER.debug("Finding AllTypesSmallCase by id: {}", alltypessmallcaseId);
        AllTypesSmallCase allTypesSmallCase = this.wmGenericDao.findById(alltypessmallcaseId);
        if (allTypesSmallCase == null){
            LOGGER.debug("No AllTypesSmallCase found with id: {}", alltypessmallcaseId);
            throw new EntityNotFoundException(String.valueOf(alltypessmallcaseId));
        }
        return allTypesSmallCase;
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
	@Override
	public AllTypesSmallCase findById(Integer alltypessmallcaseId) {
        LOGGER.debug("Finding AllTypesSmallCase by id: {}", alltypessmallcaseId);
        return this.wmGenericDao.findById(alltypessmallcaseId);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
    @Override
    public AllTypesSmallCase getByPkIdAndByteColAndShortCol(int pkId, Byte byteCol, Short shortCol) {
        Map<String, Object> pkIdAndByteColAndShortColMap = new HashMap<>();
        pkIdAndByteColAndShortColMap.put("pkId", pkId);
        pkIdAndByteColAndShortColMap.put("byteCol", byteCol);
        pkIdAndByteColAndShortColMap.put("shortCol", shortCol);

        LOGGER.debug("Finding AllTypesSmallCase by unique keys: {}", pkIdAndByteColAndShortColMap);
        AllTypesSmallCase allTypesSmallCase = this.wmGenericDao.findByUniqueKey(pkIdAndByteColAndShortColMap);

        if (allTypesSmallCase == null){
            LOGGER.debug("No AllTypesSmallCase found with given unique key values: {}", pkIdAndByteColAndShortColMap);
            throw new EntityNotFoundException(String.valueOf(pkIdAndByteColAndShortColMap));
        }

        return allTypesSmallCase;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "db123__TransactionManager")
	@Override
	public AllTypesSmallCase update(AllTypesSmallCase allTypesSmallCase) throws EntityNotFoundException {
        LOGGER.debug("Updating AllTypesSmallCase with information: {}", allTypesSmallCase);
        this.wmGenericDao.update(allTypesSmallCase);

        Integer alltypessmallcaseId = allTypesSmallCase.getPkId();

        return this.wmGenericDao.findById(alltypessmallcaseId);
    }

    @Transactional(value = "db123__TransactionManager")
	@Override
	public AllTypesSmallCase delete(Integer alltypessmallcaseId) throws EntityNotFoundException {
        LOGGER.debug("Deleting AllTypesSmallCase with id: {}", alltypessmallcaseId);
        AllTypesSmallCase deleted = this.wmGenericDao.findById(alltypessmallcaseId);
        if (deleted == null) {
            LOGGER.debug("No AllTypesSmallCase found with id: {}", alltypessmallcaseId);
            throw new EntityNotFoundException(String.valueOf(alltypessmallcaseId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "db123__TransactionManager")
	@Override
	public Page<AllTypesSmallCase> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all AllTypesSmallCases");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
    @Override
    public Page<AllTypesSmallCase> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all AllTypesSmallCases");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service db123__ for table AllTypesSmallCase to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "db123__TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

