/*Copyright (c) 2017-2018 wm9.com All Rights Reserved.
 This software is the confidential and proprietary information of wm9.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wm9.com*/

package com.mobi_22ndaug_dev.db123__.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

@Service
public class Db123__ProcedureExecutorServiceImpl implements Db123__ProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(Db123__ProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("db123__WMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;


}


